[package]
name = "quote-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
askama = "0.12"
hyper = { version = "1", features = ["full"] } 
[build-dependencies]
askama = "0.12"
